#!/usr/bin/env python3
"""Simple Code Generation Example
Shows how to use Hydra to generate specific code snippets
"""

import os
import sys

from dotenv import load_dotenv

# Setup paths
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))

from hydra.agents.base import CodeAgent


def generate_examples():
    """Generate various code examples."""
    # Create a code generation agent
    coder = CodeAgent("code_generator")

    examples = [
        {
            "title": "Data Validation Function",
            "prompt": "Create a Python function that validates if a string is a valid IPv4 address",
        },
        {
            "title": "Sorting Algorithm",
            "prompt": "Implement merge sort algorithm in Python with comments explaining each step",
        },
        {
            "title": "Design Pattern",
            "prompt": "Create a Python implementation of the Observer design pattern",
        },
        {
            "title": "File Handler",
            "prompt": "Write a Python context manager for safely reading and writing JSON files",
        },
        {
            "title": "API Response Parser",
            "prompt": "Create a function that parses nested JSON API responses and extracts specific fields with error handling",
        },
    ]

    for i, example in enumerate(examples, 1):
        print(f"\n{'='*60}")
        print(f"Example {i}: {example['title']}")
        print(f"{'='*60}")
        print(f"Prompt: {example['prompt']}")
        print("\nGenerating code...\n")

        try:
            # Generate the code
            code = coder.generate_code(example["prompt"])
            print("Generated Code:")
            print("-" * 60)
            print(code)
            print("-" * 60)

            # Save to file
            filename = f"generated_{example['title'].lower().replace(' ', '_')}.py"
            with open(filename, "w") as f:
                f.write(f'"""\n{example["title"]}\nGenerated by Hydra\n"""\n\n')
                f.write(code)
            print(f"\n✅ Saved to: {filename}")

        except Exception as e:
            print(f"❌ Error: {e}")

    print(f"\n\n🎉 Code generation complete! Generated {len(examples)} examples.")


def interactive_generation():
    """Interactive code generation mode."""
    print("\n🤖 Interactive Code Generation Mode")
    print("Type 'quit' to exit\n")

    coder = CodeAgent("interactive_coder")

    while True:
        prompt = input("\n📝 Enter your code request: ").strip()

        if prompt.lower() in ["quit", "exit", "q"]:
            print("👋 Goodbye!")
            break

        if not prompt:
            print("❌ Please enter a code request")
            continue

        print("\nGenerating code...\n")

        try:
            code = coder.generate_code(prompt)
            print("Generated Code:")
            print("=" * 60)
            print(code)
            print("=" * 60)

            save = input("\nSave to file? (y/n): ").strip().lower()
            if save == "y":
                filename = input("Filename (without .py): ").strip()
                if filename:
                    with open(f"{filename}.py", "w") as f:
                        f.write(code)
                    print(f"✅ Saved to {filename}.py")

        except Exception as e:
            print(f"❌ Error: {e}")


def main():
    """Main entry point."""
    if not os.getenv("VENICE_API_KEY"):
        print("❌ Error: VENICE_API_KEY not found in environment")
        print("Please set it in your .env file")
        return

    print("🚀 Hydra Simple Code Generation Example")
    print("=" * 60)

    if len(sys.argv) > 1 and sys.argv[1] == "--interactive":
        interactive_generation()
    else:
        generate_examples()
        print("\nTip: Run with --interactive for interactive mode")


if __name__ == "__main__":
    main()
