"""Cli module."""

import click

{% if config_format == 'yaml' %}import yaml{% endif %}
{% if config_format == 'toml' %}import toml{% endif %}
import json
from pathlib import Path

from rich.console import Console

console = Console()

@click.group()
@click.version_option(version='{{version}}')
@click.pass_context
def main(ctx):
    """{{tool_name}} - A CLI tool generated by Hydra templates."""
    ctx.ensure_object(dict)

@main.command()
@click.argument('name')
def hello(name):
    """Say hello to NAME."""
    console.print(f"Hello, [bold green]{name}[/bold green]!")

@main.command()
@click.option('--config', '-c', type=click.Path(exists=True), help='Configuration file')
def status(config):
    """Show tool status and configuration."""
    console.print(f"{{tool_name}} v{{version}}")
    console.print(f"Author: {{author}}")
    
    if config:
        config_path = Path(config)
        {% if config_format == 'yaml' %}
        with open(config_path) as f:
            config_data = yaml.safe_load(f)
        {% elif config_format == 'toml' %}
        with open(config_path) as f:
            config_data = toml.load(f)
        {% else %}
        with open(config_path) as f:
            config_data = json.load(f)
        {% endif %}
        console.print(f"Config: {config_data}")

if __name__ == '__main__':
    main()