replicaCount: 1

image:
  tag: "dev"

ingress:
  hosts:
    - host: api-dev.hydra.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

config:
  logLevel: "DEBUG"
  rateLimitRequests: "1000"